# Generated by Django 5.0 on 2024-01-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('num_plate', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('departure_city', models.CharField(default=None, max_length=100)),
                ('destination_city', models.CharField(default=None, max_length=100)),
                ('departure_date', models.DateTimeField(default=None)),
                ('image', models.ImageField(default=None, upload_to='pics')),
                ('total_seats', models.IntegerField()),
                ('booked_seats', models.IntegerField()),
                ('driver_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
    ]
