# Generated by Django 5.0 on 2023-12-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('num_plate', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('total_seats', models.IntegerField()),
                ('booked_seats', models.IntegerField()),
                ('driver_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
