# Generated by Django 5.0 on 2024-01-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='departure_date',
            field=models.DateField(default=None),
        ),
    ]
