# Generated by Django 5.0 on 2023-12-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='driver_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
