# Generated by Django 5.0 on 2024-01-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bus',
            new_name='num_plate',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_num',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
