# Generated by Django 5.0 on 2023-12-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_passenger_alter_bus_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='dest',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='prog',
            new_name='programme',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='reg_num',
            new_name='register_number',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='ticket_num',
            new_name='ticket_number',
        ),
    ]