# Generated by Django 5.0 on 2024-01-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_rename_bus_booking_num_plate_booking_seat_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver_image',
            field=models.ImageField(default=None, upload_to='driver_pics'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='image',
            field=models.ImageField(default=None, upload_to='bus_pics'),
        ),
    ]
