# Generated by Django 5.0.1 on 2024-02-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_bus_driver_image_alter_bus_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='seat_num',
            new_name='ticket_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='journey_date',
            field=models.DateField(default=None),
        ),
    ]
