# Generated by Django 5.0 on 2024-01-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_delete_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='image',
            field=models.ImageField(default='NULL', upload_to='pics'),
        ),
    ]
